# Estadística Aplicada
## Cinthya Yesenia López Díaz
### Segunda sesión
27 de Enero 2023

In [1]:
7>5

True

In [2]:
7>10

False

In [3]:
7>5 & 7>10

False

In [4]:
7+5

12

In [5]:
10-3

7

In [6]:
5*2

10

In [7]:
10/2

5.0

In [8]:
3**2

9

In [9]:
pow(3,2)

9

In [10]:
alumno1 = ['Juan', 'Perez', 23]

In [11]:
alumno1

['Juan', 'Perez', 23]

In [12]:
type(alumno1)

list

In [13]:
estadistica_g4 = ['Juan', 'Raul', 'Jimena', 'Alejandra']

In [14]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [15]:
estadistica_g4[0]

'Juan'

In [16]:
estadistica_g4[0], estadistica_g4[2]

('Juan', 'Jimena')

In [17]:
estadistica_g4[0:3]

['Juan', 'Raul', 'Jimena']

In [18]:
estadistica_g4[:]

['Juan', 'Raul', 'Jimena', 'Alejandra']

In [20]:
estadistica_g4.append('Jaime')

In [21]:
estadistica_g4

['Juan', 'Raul', 'Jimena', 'Alejandra', 'Jaime', 'Jaime']

In [22]:
estadistica_g4.remove('Jimena')

In [23]:
estadistica_g4

['Juan', 'Raul', 'Alejandra', 'Jaime', 'Jaime']

In [24]:
len(estadistica_g4)

5

In [25]:
conteo_de_lista = len(estadistica_g4)

In [26]:
conteo_de_lista

5

In [27]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [29]:
import yfinance as yf

In [30]:
import numpy as np

In [31]:
numeros = [25.7, 8, 10]

In [32]:
type(numeros)

list

In [33]:
numeros = np.array(numeros)

In [34]:
type(numeros)

numpy.ndarray

In [35]:
np.sum(numeros)

43.7

In [36]:
np.prod(numeros)

2056.0

In [37]:
np.mean(numeros)

14.566666666666668

In [38]:
np.var(numeros)

62.642222222222216

In [39]:
np.var(numeros,ddof=1)

93.96333333333332

In [40]:
np.std(numeros)

7.9146839622452525

In [41]:
np.std(numeros,ddof=1)

9.693468591445134

In [42]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.arange(7, 15)

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.full(6, 9)

array([9, 9, 9, 9, 9, 9])

In [49]:
np.random.randint(0, 10, 2)

array([4, 8])

In [52]:
np.random.seed(5)
aleatoriosu = np.random.randint(10, 30, 8)

In [53]:
aleatoriosu

array([13, 24, 25, 16, 26, 19, 18, 14])

In [55]:
aleatoriosu = np.sort(aleatoriosu)

In [56]:
aleatoriosu

array([13, 14, 16, 18, 19, 24, 25, 26])

In [57]:
aleatoriosu[2]

16

In [58]:
aleatoriosu[[2,5]]

array([16, 24])

In [60]:
aleatoriosu > 15

array([False, False,  True,  True,  True,  True,  True,  True])

In [61]:
aleatoriosu[aleatoriosu>15]

array([16, 18, 19, 24, 25, 26])

In [1]:
num2 = [10, 8, 20]

In [6]:
import numpy as np

In [9]:
num2=np.array(num2)

In [8]:
np.mean(num2)

12.666666666666666

In [10]:
num2.mean()

12.666666666666666

In [11]:
round(np.mean(np.sum(num2)))

38

In [12]:
num2.sum().mean().round()

38.0

In [16]:
numeros = [1.23, 2.45578, 5.6888785]

In [17]:
round(np.mean(np.array(numeros)), 2)

3.12

In [18]:
np.array(numeros).mean().round(2)

3.12